import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version",
};

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const supabaseClient = createClient(
      Deno.env.get("SUPABASE_URL") ?? "",
      Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "",
      { auth: { persistSession: false } }
    );

    const authHeader = req.headers.get("Authorization")!;
    const token = authHeader.replace("Bearer ", "");
    const { data: userData, error: userError } = await supabaseClient.auth.getUser(token);
    if (userError || !userData.user) throw new Error("Not authenticated");

    const { content, assignment_id } = await req.json();
    if (!content || !assignment_id) throw new Error("content and assignment_id required");

    // Verify ownership
    const { data: assignment, error: assignError } = await supabaseClient
      .from("assignments")
      .select("id, user_id")
      .eq("id", assignment_id)
      .eq("user_id", userData.user.id)
      .single();
    if (assignError || !assignment) throw new Error("Assignment not found");

    const LOVABLE_API_KEY = Deno.env.get("LOVABLE_API_KEY");
    if (!LOVABLE_API_KEY) throw new Error("LOVABLE_API_KEY not configured");

    // Use AI to analyze text for AI detection patterns
    const sampleText = content.length > 10000 ? content.slice(0, 10000) : content;

    const response = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${LOVABLE_API_KEY}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model: "google/gemini-2.5-flash",
        messages: [
          {
            role: "system",
            content: `You are an expert AI-detection analyst. Your job is to estimate how likely the given academic text would be flagged as AI-generated by detectors like Turnitin AI Detection, GPTZero, and Originality.ai.

You MUST respond with ONLY a valid JSON object. No other text, no markdown, no code blocks.

The JSON must have exactly these fields:
{
  "overall_score": <number 0-100, percentage likely to be flagged as AI>,
  "human_score": <number 0-100, percentage appearing human-written>,
  "details": "<string: 2-3 sentence analysis>"
}

## SCORING CRITERIA (use weighted analysis)

### HIGH AI indicators (each adds 10-20 points to overall_score):
- Uniform sentence length throughout (low variance in word count per sentence)
- Every paragraph follows the same structure: topic sentence → evidence → analysis → transition
- Overuse of formal transition words: "Furthermore", "Moreover", "Consequently", "Nevertheless" appearing 3+ times
- AI-signature vocabulary: "delve", "multifaceted", "tapestry", "pivotal", "nuanced", "landscape", "groundbreaking", "facilitate", "utilize"
- Absence of contractions in informal-appropriate contexts
- Perfect parallelism in every list or comparison
- "It is important to note", "It should be noted", "It is worth mentioning" appearing multiple times
- Every paragraph is 4-6 sentences with no variation

### HIGH HUMAN indicators (each subtracts 10-20 points from overall_score):
- Varied sentence lengths (mix of 8-word and 25-word sentences in same paragraph)
- Natural contractions (doesn't, it's, can't)
- Em dashes used for parenthetical thoughts
- Paragraphs vary in length (some 2 sentences, some 6)
- Some abrupt transitions between paragraphs
- Author names mentioned in flowing text ("As Smith argues...")
- Slight hedging with "arguably" or "to some extent"
- Occasional sentences starting with "And" or "But"

### SCORING RULES:
- Start at 50 (neutral) and adjust based on evidence found
- Be CONSERVATIVE: if a text shows a mix of AI and human traits, lean toward a lower AI score
- Do not penalise for good grammar or clear writing — skilled students write clearly too
- A text with mostly human indicators but some AI vocabulary should score 20-35, not 50+
- overall_score + human_score must equal 100`,
          },
          {
            role: "user",
            content: `Analyze this academic text for AI detection. Count specific indicators before scoring:\n\n${sampleText}`,
          },
        ],
        temperature: 0.1,
      }),
    });

    if (!response.ok) {
      if (response.status === 429) throw new Error("Rate limited — please try again in a moment");
      if (response.status === 402) throw new Error("AI credits exhausted — please top up");
      throw new Error("AI analysis failed");
    }

    const aiData = await response.json();
    const rawContent = aiData.choices?.[0]?.message?.content?.trim();

    // Parse JSON from the response, handling potential markdown code blocks
    let parsed;
    try {
      const cleaned = rawContent.replace(/```json\n?/g, "").replace(/```\n?/g, "").trim();
      parsed = JSON.parse(cleaned);
    } catch {
      // Fallback if JSON parse fails
      parsed = {
        overall_score: 50,
        human_score: 50,
        details: "Unable to fully analyze. Please try humanizing the text and re-checking.",
      };
    }

    return new Response(
      JSON.stringify({
        overall_score: Math.min(100, Math.max(0, Math.round(parsed.overall_score))),
        human_score: Math.min(100, Math.max(0, Math.round(parsed.human_score))),
        details: parsed.details || "Analysis complete.",
      }),
      { headers: { ...corsHeaders, "Content-Type": "application/json" }, status: 200 }
    );
  } catch (error) {
    return new Response(
      JSON.stringify({ error: error.message }),
      { headers: { ...corsHeaders, "Content-Type": "application/json" }, status: 500 }
    );
  }
});
