import LegalLayout from "@/components/legal/LegalLayout";

const Terms = () => (
  <LegalLayout title="Terms of Service" lastUpdated="16 April 2026">
    <p>These Terms form a binding agreement between you and <strong>Radudotcom Limited</strong> ("MyUniPal", "we") governing your use of the service at myunipal.io and unitaskpro.org. By creating an account you agree to these Terms, our <a href="/privacy">Privacy Policy</a> and our <a href="/acceptable-use">Acceptable Use Policy</a>.</p>

    <h2>1. The service</h2>
    <p>MyUniPal is an AI-powered writing assistant designed to help UK university students with research, drafting, structuring, referencing and editing of academic work. Output is generated by large language models and provided <strong>"as is"</strong> for your study and reference purposes.</p>

    <h2>2. Eligibility</h2>
    <p>You must be at least 18 years old and have legal capacity to enter into a contract.</p>

    <h2>3. Accounts</h2>
    <p>You are responsible for keeping your login credentials secure and for all activity under your account. Notify us immediately at <a href="mailto:support@myunipal.io">support@myunipal.io</a> of any suspected unauthorised use.</p>

    <h2>4. Academic integrity — important</h2>
    <p><strong>MyUniPal is a study aid, not a submission service.</strong> Submitting AI-generated content as your own original work is considered academic misconduct by virtually every UK university and may result in expulsion, withdrawal of degree, or other sanctions. You are solely responsible for:</p>
    <ul>
      <li>Reviewing, editing and rewriting any AI-generated content;</li>
      <li>Verifying all facts, references and citations independently;</li>
      <li>Complying with your institution's policy on AI assistance;</li>
      <li>Properly disclosing the use of AI where required.</li>
    </ul>
    <p>By using the service you accept full responsibility for how you use the output. See our <a href="/acceptable-use">Acceptable Use Policy</a>.</p>

    <h2>5. Plans, credits and billing</h2>
    <ul>
      <li>Plans are listed at <a href="/plans">myunipal.io/plans</a>. Prices are in GBP. We are <strong>not currently VAT-registered</strong>; no VAT is charged.</li>
      <li>Subscriptions renew automatically until cancelled. You can cancel any time via the customer portal in Settings.</li>
      <li>Cancellation takes effect at the end of the current billing period; you keep access until then.</li>
      <li>Credits are consumed when you generate content. Unused credits may expire at the end of your billing cycle, depending on your plan.</li>
    </ul>

    <h2>6. Refunds</h2>
    <p>Because each generation immediately delivers digital content, you expressly waive your 14-day cooling-off right under the Consumer Contracts (Information, Cancellation and Additional Charges) Regulations 2013 the moment you click "Generate". See our <a href="/refund">Refund Policy</a> for full detail and exceptional cases.</p>

    <h2>7. Intellectual property</h2>
    <ul>
      <li><strong>Your prompts and inputs:</strong> remain yours.</li>
      <li><strong>Generated output:</strong> to the extent we hold any rights, we assign them to you for personal study use, subject to compliance with these Terms. You may not resell or republish output as a commercial product.</li>
      <li><strong>Our platform:</strong> all code, branding, design and trademarks are owned by Radudotcom Limited.</li>
    </ul>

    <h2>8. Acceptable use</h2>
    <p>You must not use the service to: produce unlawful, defamatory or infringing content; generate content for re-sale to third parties as a ghostwriting business; circumvent rate limits; reverse-engineer the service; misrepresent AI output as human-written in contexts where disclosure is required; or attempt to access other users' data. Violations may result in immediate suspension without refund.</p>

    <h2>9. Service availability</h2>
    <p>We aim for high uptime but do not guarantee uninterrupted service. We may perform maintenance, update features, or temporarily suspend the service. Where third-party AI providers (e.g. OpenAI, Google) are unavailable, generation may fail; failed generations are credited back automatically.</p>

    <h2>10. Liability</h2>
    <p>To the maximum extent permitted by law:</p>
    <ul>
      <li>The service is provided "as is" without warranties of accuracy, fitness for purpose or non-infringement.</li>
      <li>We are not liable for academic outcomes, grades, misconduct findings, or loss of academic standing arising from your use of the output.</li>
      <li>Our total liability in any 12-month period is capped at the greater of £100 or the fees you paid us in that period.</li>
      <li>Nothing limits liability for death or personal injury caused by negligence, fraud, or any other liability that cannot be excluded by UK law.</li>
    </ul>

    <h2>11. Suspension and termination</h2>
    <p>We may suspend or terminate your account immediately for breach of these Terms, suspected fraud, or non-payment. You may close your account at any time via Settings → Delete my account.</p>

    <h2>12. Changes to terms</h2>
    <p>We may update these Terms; material changes will be notified by email at least 14 days before they take effect. Continued use after the effective date constitutes acceptance.</p>

    <h2>13. Governing law</h2>
    <p>These Terms are governed by the laws of England and Wales. Disputes will be subject to the exclusive jurisdiction of the English courts.</p>

    <h2>14. Contact</h2>
    <p><strong>Radudotcom Limited</strong> (company no. 16125458), registered office: 59 Union Street, Dunstable, England, LU6 1EX. Email: <a href="mailto:support@myunipal.io">support@myunipal.io</a>.</p>
  </LegalLayout>
);

export default Terms;
